# Generated by Django 5.2 on 2025-05-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_image_url_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.TextField(),
        ),
    ]
